# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='desc', verbose_name='Descripton'),
            preserve_default=False,
        ),
    ]
